[package]
name = "krust"
version = "0.1.0"
authors = ["Kartikaya Gupta"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
